project:
  type: website

website:
  title: "Spotify Dashboard"
  favicon: images/logo.png
  site-url: https://vineelnekkanti.github.io/spotify-dashboard/
  repo-url: https://github.com/vineelnekkanti/spotify-dashboard
  sidebar:
    title: "Spotify Dashboard"
    search: true
    contents: 
      - href: index.qmd
        text: Home
      - href: dashboard.qmd
        text: Dashboard
      - href: about.qmd
        text: About Me

format:
  html:
    theme: [cosmo, custom.scss]
    highlight-style: atom-one-dark
    toc: true