project:
  type: website

website:
  title: "Spotify Dashboard"
  sidebar:
    contents:
      - href: dashboard.qmd
        text: Dashboard

format:
  html:
    theme: [cosmo, custom.scss]
    toc: true